# Generated by Django 6.0.4 on 2026-04-27 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('fire', 'Fire'), ('threat', 'Active Threat / Intruder'), ('mental_health', 'Mental Health Crisis'), ('assault', 'Assault / Harassment'), ('missing', 'Missing Person'), ('infrastructure', 'Infrastructure Failure')], max_length=20)),
                ('severity', models.CharField(choices=[('P1', 'Critical - Immediate danger'), ('P2', 'High - Urgent response'), ('P3', 'Medium - Monitor situation'), ('P4', 'Low - Non-emergency')], default='P3', max_length=2)),
                ('location_building', models.CharField(max_length=100)),
                ('location_room', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open - Not yet assigned'), ('assigned', 'Assigned - Responder en route'), ('in_progress', 'In Progress - On scene'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('evacuate', 'Evacuate Building'), ('shelter', 'Shelter in Place'), ('lockdown', 'Lockdown'), ('all_clear', 'All Clear'), ('info', 'Informational')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('affected_buildings', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_ra', models.BooleanField(default=False)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.incident')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='myapp.student'),
        ),
    ]
