# Generated by Django 6.0.4 on 2026-04-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responderassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='responderassignment',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='responderassignment',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location_building',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location_room',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('accident', 'Accident'), ('crime', 'Crime'), ('medical', 'Medical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='CampusAlert',
        ),
        migrations.DeleteModel(
            name='ResponderAssignment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
