# Generated by Django 6.0.4 on 2026-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_responderassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('accident', 'Accident'), ('crime', 'Crime'), ('medical', 'Medical'), ('emergency', 'Emergency')], max_length=20),
        ),
    ]
